apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: naicha-api
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "30"
spec:
  tls:
    - hosts:
        - api.staging.example.com
      secretName: tls-naicha-staging
  rules:
    - host: api.staging.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: naicha-api
                port:
                  number: 80
