"""add_analytics_events_table

Revision ID: 5c34c68b9b8c
Revises: 20251108_order_pickup_code
Create Date: 2025-11-23 07:56:59.775523
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建 analytics_events 表及索引
    op.create_table(
        "analytics_events",
        sa.Column("event_id", sa.UUID(), nullable=False, comment="事件唯一标识(UUID v4,前端生成)"),
        sa.Column("user_id", sa.Integer(), nullable=True, comment="用户ID(NULL表示匿名用户)"),
        sa.Column(
            "session_id", sa.String(length=80), nullable=True, comment="会话标识(用户或匿名会话)"
        ),
        sa.Column(
            "event_type", sa.String(length=20), nullable=False, comment="事件类型: event/page/user"
        ),
        sa.Column(
            "event_name",
            sa.String(length=50),
            nullable=False,
            comment="事件名称: add_to_cart/page_view等",
        ),
        sa.Column(
            "event_timestamp",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="前端事件发生时间戳(UTC)",
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="自定义事件属性(JSON格式)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="NOW()",
            nullable=False,
            comment="服务端接收时间(UTC)",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_analytics_events")),
        comment="用户行为埋点事件表",
    )
    op.create_index(
        "idx_analytics_created_at",
        "analytics_events",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index(
        "idx_analytics_event_name_time",
        "analytics_events",
        ["event_name", "event_timestamp"],
        unique=False,
        postgresql_ops={"event_timestamp": "DESC"},
    )
    op.create_index(
        "idx_analytics_session_time",
        "analytics_events",
        ["session_id", "event_timestamp"],
        unique=False,
        postgresql_ops={"event_timestamp": "DESC"},
    )
    op.create_index(
        "idx_analytics_user_event_time",
        "analytics_events",
        ["user_id", "event_timestamp"],
        unique=False,
        postgresql_ops={"event_timestamp": "DESC"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 回滚 analytics_events 表及索引
    op.drop_index(
        "idx_analytics_user_event_time",
        table_name="analytics_events",
        postgresql_ops={"event_timestamp": "DESC"},
    )
    op.drop_index(
        "idx_analytics_session_time",
        table_name="analytics_events",
        postgresql_ops={"event_timestamp": "DESC"},
    )
    op.drop_index(
        "idx_analytics_event_name_time",
        table_name="analytics_events",
        postgresql_ops={"event_timestamp": "DESC"},
    )
    op.drop_index(
        "idx_analytics_created_at",
        table_name="analytics_events",
        postgresql_ops={"created_at": "DESC"},
    )
    op.drop_table("analytics_events")
    # ### end Alembic commands ###
